# Generated by Django 2.2.5 on 2019-09-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trans_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
