# Generated by Django 2.2.5 on 2019-09-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190910_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_issued',
            field=models.BooleanField(default=False),
        ),
    ]
