# Generated by Django 2.2.5 on 2019-09-11 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_ticket_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
