# Generated by Django 2.2.5 on 2019-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190911_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
