# Generated by Django 2.2.5 on 2019-10-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20191015_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', to_field='account'),
        ),
    ]
