# Generated by Django 2.2.5 on 2019-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='company_users',
            field=models.ManyToManyField(blank=True, to='companies.CompanyUser'),
        ),
    ]
