# Generated by Django 2.2.5 on 2019-09-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20190907_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
