# Generated by Django 2.2.5 on 2019-09-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190907_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='company_users',
            new_name='region_users',
        ),
    ]
