# Generated by Django 2.2.5 on 2019-09-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20190907_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
