# Generated by Django 2.2.5 on 2019-09-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190907_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_users',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Region'),
        ),
    ]
